default:
  plugins:
    - autolink
    - image
    - link
  paste_data_images: true
  images_upload_base_path: '../app/assets/images'
  images_upload_credentials: true

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table
